name: 'Fix The Release (do not use)'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Keycloak branch'
        required: true
      version:
        description: 'New version'
        required: true
      previous-version:
        description: 'Old version'
        required: true

concurrency: rel-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:

  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: ${{ inputs.version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Release branch: ${{ inputs.branch }}  " >> $GITHUB_STEP_SUMMARY
          echo "Previous Keycloak version: ${{ inputs.previous-version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Workflow branch: ${{ github.ref_name }}  " >> $GITHUB_STEP_SUMMARY

  env:
    uses: ./.github/workflows/x-env.yml

  # no tag creation (already done)

  # Github release is also already created

  keycloak:
    name: Keycloak
    needs: [env, create-tags, create-gh-releases]
    uses: ./.github/workflows/x-keycloak-no-mvn-deploy.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      mvn-deploy-options: ${{ needs.env.outputs.mvn-deploy-options }}
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak-container:
    name: Keycloak Container
    needs: [env, create-tags, keycloak]
    uses: ./.github/workflows/x-keycloak-container.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      quay-org: ${{ needs.env.outputs.quay-org }}
      docker-org: ${{ needs.env.outputs.docker-org }}
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  keycloak-operator:
    name: Keycloak Operator
    needs: [env, create-tags,keycloak-container]
    uses: ./.github/workflows/x-keycloak-operator.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      quay-org: ${{ needs.env.outputs.quay-org }}
      docker-org: ${{ needs.env.outputs.docker-org }}
      version: ${{ github.event.inputs.version }}
      previous-version: ${{ github.event.inputs.previous-version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  publish-keycloak-operator-hub:
    name: Publish Keycloak Operator to OperatorHub
    needs: [ env, keycloak-operator]
    uses: ./.github/workflows/x-keycloak-operator-hub-publish.yml
    with:
      version: ${{ github.event.inputs.version }}
      community-operators-org: ${{ needs.env.outputs.community-operators-org }}
      prod-operators-org: ${{ needs.env.outputs.prod-operators-org }}
      release-bot-email: ${{ needs.env.outputs.release-bot-email }}
      release-bot-name: ${{ needs.env.outputs.release-bot-name }}
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

  publish-gh-releases:
    name: Publish releases
    needs: [ env, keycloak ]
    uses: ./.github/workflows/x-publish-gh-releases.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    name: Publish NPM packages
    needs: [ env, keycloak ]
    uses: ./.github/workflows/x-publish-npm.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
