name: 'Fix The Release (do not use)'

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Keycloak branch'
        required: true
      version:
        description: 'New version'
        required: true
      previous-version:
        description: 'Old version'
        required: true

concurrency: rel-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:

  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Version: ${{ inputs.version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Release branch: ${{ inputs.branch }}  " >> $GITHUB_STEP_SUMMARY
          echo "Previous Keycloak version: ${{ inputs.previous-version }}  " >> $GITHUB_STEP_SUMMARY
          echo "Workflow branch: ${{ github.ref_name }}  " >> $GITHUB_STEP_SUMMARY

  env:
    uses: ./.github/workflows/x-env.yml

  # no tag creation (already done)

  # Github release is also already created

  keycloak:
    name: Keycloak
    needs: [env]
    uses: ./.github/workflows/x-keycloak-no-mvn-deploy.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      mvn-deploy-options: ${{ needs.env.outputs.mvn-deploy-options }}
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  publish-gh-releases:
    name: Publish releases
    needs: [ env, keycloak ]
    uses: ./.github/workflows/x-publish-gh-releases.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    name: Publish NPM packages
    needs: [ env, keycloak ]
    uses: ./.github/workflows/x-publish-npm.yml
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
