name: Release Nightly

on:
  workflow_dispatch:

concurrency: rel-${{ github.ref }}

jobs:

  create-tags:
    name: Create tags
    uses: ./.github/workflows/x-create-tags.yml
    with:
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-nodejs-admin:
    name: Keycloak Node.js Admin Client
    needs: [create-tags]
    uses: ./.github/workflows/x-keycloak-nodejs-admin.yml
    with:
      version: 999-SNAPSHOT
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-admin-console:
    name: Keycloak Admin Console
    needs: [create-tags,keycloak-nodejs-admin]
    uses: ./.github/workflows/x-keycloak-admin-console.yml
    with:
      version: 999-SNAPSHOT
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_SNAPSHOTS_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak:
    name: Keycloak
    needs: [create-tags,keycloak-admin-console]
    uses: ./.github/workflows/x-keycloak.yml
    with:
      version: 999-SNAPSHOT
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_SNAPSHOTS_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak-container:
    name: Keycloak Container
    needs: [create-tags,keycloak]
    uses: ./.github/workflows/x-keycloak-container.yml
    with:
      version: 999-SNAPSHOT
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      QUAY_ORG: ${{ secrets.QUAY_ORG }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  keycloak-operator:
    name: Keycloak Operator
    needs: [create-tags,keycloak-container]
    uses: ./.github/workflows/x-keycloak-operator.yml
    with:
      version: 999-SNAPSHOT
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_SNAPSHOTS_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      QUAY_ORG: ${{ secrets.QUAY_ORG }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  keycloak-documentation:
    name: Keycloak Documentation
    needs: [create-tags]
    uses: ./.github/workflows/x-keycloak-documentation.yml
    with:
      version: 999-SNAPSHOT
      tag: nightly
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
