name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
      version:
        required: true

concurrency: rel-${{ github.ref }}

jobs:

  create-tags:
    name: Create tags
    uses: ./.github/workflows/x-create-tags.yml
    with:
      tag: ${{ github.event.inputs.version }}
      branch: ${{ github.event.inputs.branch }}
      set-versions: true
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  create-gh-releases:
    name: Create Github releases
    needs: [create-tags]
    uses: ./.github/workflows/x-create-gh-releases.yml
    with:
      tag: ${{ github.event.inputs.version }}
      prerelease: false
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-nodejs-admin:
    name: Keycloak Node.js Admin Client
    needs: [create-tags, create-gh-releases]
    uses: ./.github/workflows/x-keycloak-nodejs-admin.yml
    with:
      tag: ${{ github.event.inputs.version }}
      version: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-admin-console:
    name: Keycloak Admin Console
    needs: [create-tags,keycloak-nodejs-admin]
    uses: ./.github/workflows/x-keycloak-admin-console.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_RELEASES_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak:
    name: Keycloak
    needs: [create-tags, create-gh-releases, keycloak-admin-console]
    uses: ./.github/workflows/x-keycloak.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_RELEASES_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak-container:
    name: Keycloak Container
    needs: [create-tags,keycloak]
    uses: ./.github/workflows/x-keycloak-container.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      QUAY_ORG: ${{ secrets.QUAY_ORG }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  keycloak-operator:
    name: Keycloak Operator
    needs: [create-tags,keycloak-container]
    uses: ./.github/workflows/x-keycloak-operator.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_RELEASES_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      QUAY_ORG: ${{ secrets.QUAY_ORG }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  keycloak-documentation:
    name: Keycloak Documentation
    needs: [create-tags, create-gh-releases]
    uses: ./.github/workflows/x-keycloak-documentation.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-quickstarts:
    name: Keycloak QuickStarts
    needs: [create-tags,keycloak]
    uses: ./.github/workflows/x-keycloak-quickstarts.yml
    with:
      tag: ${{ github.event.inputs.version }}
      target-branch: latest
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-gh-releases:
    name: Publish releases
    needs: [keycloak, keycloak-documentation, keycloak-nodejs-admin]
    uses: ./.github/workflows/x-publish-gh-releases.yml
    with:
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    name: Publish NPM packages
    needs: [keycloak-nodejs-admin]
    uses: ./.github/workflows/x-publish-npm.yml
    with:
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
