name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
      version:
        required: true

concurrency: keycloak-release

jobs:

  create-tags:
    name: Update tags
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repository:
          - keycloak
          - keycloak-admin-ui
          - keycloak-documentation
          - keycloak-nodejs-admin-client

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: '${{ secrets.GH_ORG }}/${{ matrix.repository }}'
        token: ${{ secrets.GH_TOKEN }}
        path: ${{ matrix.repository }}
        ref: ${{ github.event.inputs.branch }}

    - name: Set versions
      working-directory: ${{ matrix.repository }}
      run: |
        ./set-version.sh ${{ github.event.inputs.version }}
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git commit -a -m "Set version to ${{ github.event.inputs.version }}"

    - name: Push tag
      working-directory: ${{ matrix.repository }}
      run: |
        git tag -f ${{ github.event.inputs.version }}
        git push origin ${{ github.event.inputs.version }} --force

  keycloak-nodejs-admin:
    name: Keycloak Node.js Admin Client
    needs: [create-tags]
    uses: ./.github/workflows/x-keycloak-nodejs-admin.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  keycloak-admin-console:
    name: Keycloak Admin Console
    needs: [create-tags,keycloak-nodejs-admin]
    uses: ./.github/workflows/x-keycloak-admin-console.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_RELEASES_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak:
    name: Keycloak
    needs: [create-tags,keycloak-admin-console]
    uses: ./.github/workflows/x-keycloak.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_RELEASES_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

  keycloak-container:
    name: Keycloak Container
    needs: [create-tags,keycloak]
    uses: ./.github/workflows/x-keycloak-container.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      QUAY_ORG: ${{ secrets.QUAY_ORG }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  keycloak-operator:
    name: Keycloak Operator
    needs: [create-tags,keycloak-container]
    uses: ./.github/workflows/x-keycloak-operator.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      MVN_URL: ${{ secrets.MVN_SNAPSHOTS_URL }}
      MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
      MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
      QUAY_ORG: ${{ secrets.QUAY_ORG }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

  keycloak-documentation:
    name: Keycloak Documentation
    needs: [create-tags]
    uses: ./.github/workflows/x-keycloak-documentation.yml
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_ORG: ${{ secrets.GH_ORG }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
