name: Re-spin Containers

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

concurrency: rel-${{ github.ref }}

jobs:

  env:
    uses: ./.github/workflows/x-env.yml

  keycloak-container:
    name: Keycloak Container
    uses: ./.github/workflows/x-keycloak-container.yml
    needs: [env]
    with:
      gh-org: ${{ needs.env.outputs.gh-org }}
      quay-org: ${{ needs.env.outputs.quay-org }}
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
