name: Test

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
      version:
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:

  echo:
    name: Update nightly tags
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "${{ env.VERSION }}"