name: X Create tags
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: main
      set-versions:
        required: false
        type: boolean
        default: false
    secrets:
      GH_ORG:
        required: true
      GH_TOKEN:
        required: true
jobs:
  create-tags:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - keycloak
          - keycloak-admin-ui
          - keycloak-documentation
          - keycloak-nodejs-admin-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "${{ secrets.GH_ORG }}/${{ matrix.repository }}"
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ matrix.repository }}
          ref: ${{ inputs.branch }}

      - name: Create version commit
        if: inputs.set-versions
        working-directory: ${{ matrix.repository }}
        run: |
          ./set-version.sh ${{ inputs.tag }}
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Set version to ${{ inputs.tag }}"

      - name: Tag commit
        working-directory: ${{ matrix.repository }}
        run: git tag --force ${{ inputs.tag }}

      - name: Push changes
        working-directory: ${{ matrix.repository }}
        run:  |
          git push origin ${{ inputs.branch }} --force
          git push origin --force --tags
