name: X Keycloak Web

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      server-version:
        required: true
        default: skip
        type: string
      js-version:
        required: true
        default: skip
        type: string
      client-version:
        required: true
        default: skip
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  upload-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak.github.io'
          token: ${{ secrets.GH_TOKEN }}

      - name: Download api-docs for server release
        if: ${{ inputs.server-version != 'skip' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release -R ${{ inputs.gh-org }}/keycloak download ${{ inputs.server-version }} -p keycloak-api-docs-${{ inputs.server-version }}.zip
          unzip keycloak-api-docs-${{ inputs.server-version }}.zip
          rm keycloak-api-docs-${{ inputs.server-version }}.zip
          mv keycloak-api-docs-${{ inputs.server-version }} docs-api/${{ inputs.server-version }}

          cd docs-api
          rm latest
          ln -s ${{ inputs.server-version }} latest
      - name: Download documentation for server release
        if: ${{ inputs.server-version != 'skip' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release -R ${{ inputs.gh-org }}/keycloak download ${{ inputs.server-version }} -p keycloak-documentation-${{ inputs.server-version }}.zip
          unzip keycloak-documentation-${{ inputs.server-version }}.zip
          rm keycloak-documentation-${{ inputs.server-version }}.zip
          mv keycloak-documentation-${{ inputs.server-version }} docs/${{ inputs.server-version }}

          cd docs
          rm latest
          ln -s ${{ inputs.server-version }} latest
      - name: Commit to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add docs/${{ inputs.server-version }}
          git add docs/latest
          git add docs-api/${{ inputs.server-version }}
          git add docs-api/latest

          git commit -m "Documentation for ${{ inputs.server-version }}"
          git push origin main:main

  add-version:
    runs-on: ubuntu-latest
    needs: [upload-docs]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak-web'
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Add version server
        if: ${{ inputs.server-version != 'skip' }}
        run: |
          ./add-version.sh ${{ inputs.server-version }}
          echo "SERVER_COMMIT_MSG=Keycloak ${{ inputs.server-version }} release" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Add version keycloak-js
        if: ${{ inputs.js-version != 'skip' }}
        run: |
          ./add-version.sh ${{ inputs.js-version }} keycloak-js
          echo "JS_COMMIT_MSG=Keycloak JS ${{ inputs.js-version }} release" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Add version keycloak-client
        if: ${{ inputs.client-version != 'skip' }}
        run: |
          ./add-version.sh ${{ inputs.client-version }} keycloak-client
          echo "CLIENT_COMMIT_MSG=Keycloak Client Libs ${{ inputs.client-version }} release" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit to repository
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add --all
          git commit -m "$SERVER_COMMIT_MSG\n$JS_COMMIT_MSG\n$CLIENT_COMMIT"
          git push origin main:main

      - name: Attach Keycloak Server release notes to GH release
        if: ${{ inputs.server-version != 'skip' }}
        run: gh release edit --repo keycloak/keycloak --notes-file cache/releases/keycloak/${{ inputs.server-version }}/gh-release-notes.html ${{ inputs.server-version }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
