name: X Keycloak Documentation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_ORG:
        required: true
      GH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Checkout repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ secrets.GH_ORG }}/keycloak-documentation'
          token: ${{ secrets.GH_TOKEN }}
          path: keycloak-documentation
          ref: ${{ inputs.tag }}

      - name: Build documentation
        working-directory: ./keycloak-documentation
        run: mvn -nsu -B clean install -DskipTests -Dlatest

      - name: Upload documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ ${{ inputs.tag }} == 'nightly' ]; then
            gh release view nightly | grep 'asset:' | cut -f 2 | xargs -I '{}' gh release delete-asset nightly '{}' -y
          else
            gh release create ${{ inputs.tag }}
          fi
          gh release upload ${{ inputs.tag }} ./dist/target/keycloak-documentation-${{ inputs.version }}.zip
        working-directory: ./keycloak-documentation