name: X Keycloak QuickStarts

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      server-version:
        required: true
        default: skip
        type: string
      js-version:
        required: true
        default: skip
        type: string
      client-version:
        required: true
        default: skip
        type: string
      target-branch:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak-quickstarts'
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.target-branch }}

      - name: Set version for server or js
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [[ "${{ inputs.server-version }}" != "skip" ]]; then
            ./set-server-version.sh ${{ inputs.server-version }}
            git commit -a -m "Set server version to ${{ inputs.server-version }}"          
          fi
          if [[ "${{ inputs.js-version }}" != "skip" ]]; then
            ./set-js-version.sh ${{ inputs.js-version }}
            git commit -a -m "Set keycloak-js version to ${{ inputs.js-version }}"          
          fi
          if [[ "${{ inputs.client-version }}" != "skip" ]]; then
            ./set-client-version.sh ${{ inputs.client-version }}
            git commit -a -m "Set keycloak client libs version to ${{ inputs.client-version }}"          
          fi

      - name: Push changes
        run: git push origin ${{ inputs.target-branch }}

      - name: Show QuickStart branch
        run: echo "https://github.com/${{ inputs.gh-org }}/keycloak-quickstarts/tree/${{ inputs.target-branch }}  " >> $GITHUB_STEP_SUMMARY
