name: X Keycloak Node.js Connect

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.gh-org }}/keycloak-nodejs-connect
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.tag }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
          cache: npm

      - name: Create package tarball
        run: |
          npm pack
          mv -T *.tgz keycloak-nodejs-connect.tgz

      - name: Upload to GitHub Releases
        run: |
          for i in `gh release view ${{ inputs.tag }} --json assets --jq '.assets[].name'`; do 
            test -f $i || gh release delete-asset ${{ inputs.tag }} $i -y
          done
          gh release upload ${{ inputs.tag }} keycloak-nodejs-connect.tgz --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
