name: X Keycloak Documentation

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak-documentation'
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.tag }}

      - name: Build
        run: mvn -nsu -B clean install -DskipTests -Dlatest

      - name: Upload to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd ./dist/target
          for i in `gh release view ${{ inputs.tag }} --json assets --jq '.assets[].name'`; do 
            test -f $i || gh release delete-asset ${{ inputs.tag }} $i -y
          done
          gh release upload ${{ inputs.tag }} keycloak-documentation-${{ inputs.version }}.zip --clobber

      - name: Show GitHub Release artifacts
        run: |
          echo https://github.com/${{ inputs.gh-org }}/keycloak-documentation/releases/download/${{ inputs.version }}/keycloak-documentation-${{ inputs.version }}.zip >> $GITHUB_STEP_SUMMARY
