name: X Keycloak Admin Console

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      MVN_USERNAME:
        required: true
      MVN_TOKEN:
        required: true
      GPG_PASSPHRASE:
        required: true
      GPG_PRIVATE_KEY:
        required: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Maven Config for Nexus
        if: inputs.gh-org == 'keycloak'
        run: |
          echo "MAVEN_ID=ossrh" >> $GITHUB_ENV
          echo "MAVEN_OPTS=" >> $GITHUB_ENV
      - name: Maven Config for GitHub
        if: inputs.gh-org == 'keycloak-rel-testing'
        run: |
          echo "MAVEN_ID=github" >> $GITHUB_ENV
          echo "MAVEN_OPTS=-DskipNexus -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/keycloak-rel-testing/maven" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: 11
          server-id: ${{ env.MAVEN_ID }}
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak-ui'
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.tag }}

      - name: Deploy to Maven
        env:
          MAVEN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MVN_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        working-directory: ./keycloak-theme
        run: |
          mvn -nsu -B -Prelease,gpg ${{ env.MAVEN_OPTS }} clean deploy | tee deploy.log

      - name: Show Maven artifacts
        working-directory: ./keycloak-theme
        run: |
          cat deploy.log | grep "Uploaded to" | grep -o "https://[^ ]*" | grep -v '.xml$' | grep -v '.asc$' | grep -v '.pom$' | grep -v 'javadoc.jar$' | grep -v 'sources.jar$' | xargs -I {} echo "{}  " >> $GITHUB_STEP_SUMMARY
