name: X Keycloak Web

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      component:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  upload-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak.github.io'
          token: ${{ secrets.GH_TOKEN }}

      - name: Download api-docs for server release
        if: ${{ inputs.component == 'keycloak-server' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release -R ${{ inputs.gh-org }}/keycloak download ${{ inputs.version }} -p keycloak-api-docs-${{ inputs.version }}.zip
          unzip keycloak-api-docs-${{ inputs.version }}.zip
          rm keycloak-api-docs-${{ inputs.version }}.zip
          mv keycloak-api-docs-${{ inputs.version }} docs-api/${{ inputs.version }}

          cd docs-api
          rm latest
          ln -s ${{ inputs.version }} latest
      - name: Download documentation for server release
        if: ${{ inputs.component == 'keycloak-server' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release -R ${{ inputs.gh-org }}/keycloak download ${{ inputs.version }} -p keycloak-documentation-${{ inputs.version }}.zip
          unzip keycloak-documentation-${{ inputs.version }}.zip
          rm keycloak-documentation-${{ inputs.version }}.zip
          mv keycloak-documentation-${{ inputs.version }} docs/${{ inputs.version }}
          cd docs
          rm latest
          ln -s ${{ inputs.version }} latest
      - name: Commit to repository
        if: ${{ inputs.component == 'keycloak-server' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add docs/${{ inputs.version }}
          git add docs/latest
          git add docs-api/${{ inputs.version }}
          git add docs-api/latest

          git commit -m "Documentation for $${{ inputs.component }} version ${{ inputs.version }}"
          git push origin main:main

  add-version:
    runs-on: ubuntu-latest
    needs: [upload-docs]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ inputs.gh-org }}/keycloak-web'
          token: ${{ secrets.GH_TOKEN }}
          
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Add version of the component to keycloak-web
        run: |
          if [[ "${{ inputs.component }}" == "keycloak-server" ]]; then
            ./add-version.sh ${{ inputs.version }}
            COMMIT_MSG="Keycloak Server ${{ inputs.version }} release"
          elif [[ "${{ inputs.component }}" == "keycloak-js" ]]; then
            ./add-version.sh ${{ inputs.version }} keycloak-js
            COMMIT_MSG="Keycloak JS ${{ inputs.version }} release"
          elif [[ "${{ inputs.component }}" == "keycloak-client" ]]; then
            ./add-version.sh ${{ inputs.version }} keycloak-client
            COMMIT_MSG="Keycloak Client Libs ${{ inputs.version }} release"
          elif [[ "${{ inputs.component }}" == "keycloak-nodejs-connect" ]]; then
            ./add-version.sh ${{ inputs.version }} keycloak-nodejs-connect
            COMMIT_MSG="Keycloak Nodejs Connect ${{ inputs.version }} release"
          else
            echo "Announce of component '${{ inputs.component }}' is not supported." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add --all
          git commit -m "$COMMIT_MSG"
          git push origin main:main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Attach release notes of the component to GH release
        run: |
          if [[ "${{ inputs.component }}" == "keycloak-server" ]]; then
            gh release edit --repo keycloak/keycloak --notes-file cache/releases/keycloak/${{ inputs.version }}/gh-release-notes.html ${{ inputs.version }}
          elif [[ "${{ inputs.component }}" == "keycloak-js" ]]; then
            gh release edit --repo keycloak/keycloak-js --notes-file cache/releases/keycloak-js/${{ inputs.version }}/gh-release-notes.html ${{ inputs.version }}
          elif [[ "${{ inputs.component }}" == "keycloak-client" ]]; then
            gh release edit --repo keycloak/keycloak-client --notes-file cache/releases/keycloak-client/${{ inputs.version }}/gh-release-notes.html ${{ inputs.version }}
          elif [[ "${{ inputs.component }}" == "keycloak-nodejs-connect" ]]; then
            gh release edit --repo keycloak/keycloak-nodejs-connect --notes-file cache/releases/keycloak-nodejs-connect/${{ inputs.version }}/gh-release-notes.html ${{ inputs.version }}
          else
            echo "Attache release notes of the component '${{ inputs.component }}' is not supported." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
