name: X Keycloak Documentation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      GH_ORG:
        required: true
      GH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Checkout Repository
        uses: actions/checkout@v3.0.0
        with:
          repository: '${{ secrets.GH_ORG }}/keycloak-documentation'
          token: ${{ secrets.GH_TOKEN }}
          ref: ${{ inputs.tag }}

      - name: Build
        run: mvn -nsu -B clean install -DskipTests -Dlatest

      - name: Upload to GitHub Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh release upload ${{ inputs.tag }} ./dist/target/keycloak-documentation-${{ inputs.version }}.zip
